CREATE DATABASE Hamo;
USE Hamo;

DESC USER;
SELECT * FROM USER;


DROP TABLE my_server;
CREATE TABLE my_server(
    id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    servername VARCHAR(255) NOT NULL,
    user_id BIGINT(20) NOT NULL,
    FOREIGN KEY(user_id) REFERENCES USER(id) ON DELETE CASCADE
);
SELECT * FROM my_server;

DROP TABLE myServerPost;
CREATE TABLE myServerPost(
    id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL,
    content TEXT NOT NULL,
    create_date DATETIME DEFAULT NOW(),
    myServer_id INT(11) UNSIGNED NOT NULL ,
    FOREIGN KEY(myServer_id) REFERENCES myServer(id) ON DELETE CASCADE
);


SELECT * FROM myServerPost;